name: Frontend CI/CD

on:
  push:
    branches: [main, dev]
    paths:
      - 'fe/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'fe/**'

permissions:
  contents: write
  issues: write
  pull-requests: write
  organization-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fe

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './fe/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env

      - name: Lint
        run: |
          npm run lint
          npm run prettier

      - name: Type check
        run: tsc --noEmit

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync ./out s3://fe-youtube-deploy --delete

      - name: Invalidate CloudFront
        if: github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.AUTO_ACTIONS_TOKEN }}
          script: |
            const PROJECT = {
              ID: '${{ secrets.PROJECT_ID }}',
              STATUS_FIELD: '${{ secrets.STATUS_FIELD_ID }}',
              COLUMNS: {
                BACKLOG: '17052d30',
                SPRINT_BACKLOG: '2b4b3335',
                IN_PROGRESS: 'dc54b4f8',
                IN_REVIEW: '3fdc4773',
                DONE: '98236657'
              }
            };

            async function addToProject(contentId) {
              const mutation = `
                mutation($projectId: ID!, $contentId: ID!) {
                  addProjectV2ItemById(input: {
                    projectId: $projectId
                    contentId: $contentId
                  }) {
                    item {
                      id
                    }
                  }
                }
              `;
              
              const result = await github.graphql(mutation, {
                projectId: PROJECT.ID,
                contentId: contentId
              });
              
              return result.addProjectV2ItemById.item.id;
            }

            async function moveIssueToColumn(contentId, columnId) {
              try {
                const itemId = await addToProject(contentId);
                console.log('Item added with ID:', itemId);
                
                const mutation = `
                  mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $columnId: String!) {
                    updateProjectV2ItemFieldValue(
                      input: {
                        projectId: $projectId
                        itemId: $itemId
                        fieldId: $fieldId
                        value: { 
                          singleSelectOptionId: $columnId
                        }
                      }
                    ) {
                      projectV2Item {
                        id
                      }
                    }
                  }
                `;
                
                await github.graphql(mutation, {
                  projectId: PROJECT.ID,
                  itemId: itemId,
                  fieldId: PROJECT.STATUS_FIELD,
                  columnId: columnId
                });
                
                console.log('Status updated successfully');
              } catch (error) {
                if (!error.message.includes('already exists')) {
                  console.error('Error:', error);
                  throw error;
                }
              }
            }

            if (context.eventName === 'pull_request') {
              const prId = context.payload.pull_request.node_id;
              
              if (context.payload.action === 'opened' || context.payload.action === 'reopened') {
                await moveIssueToColumn(prId, PROJECT.COLUMNS.IN_REVIEW);
              } else if (context.payload.action === 'closed' && context.payload.pull_request.merged) {
                await moveIssueToColumn(prId, PROJECT.COLUMNS.DONE);
              }
            }
